---
- name: Install IPA server
  hosts: ipaserver
  become: true

  pre_tasks:
    - name: Update OpenSSH to the latest version
      dnf:
        name:
          - openssh
          - openssh-server
          - openssh-clients
        state: latest
        update_cache: yes

    - name: Update host files
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ ansible_default_ipv4.address }} {{ ipaserver_hostname}} {{ ipaserver_hostname }}"
        state: present

    - name: Ensure hostname is properly set
      ansible.builtin.hostname:
        name: "{{ ipaserver_hostname}}"

  roles:
    - role: freeipa.ansible_freeipa.ipaserver
      state: present

  # tasks:
  #   - name: Set a persistent hostname
  #     command: hostnamectl set-hostname ipa-server.rts.local
  #   - name: Update OpenSSH to the latest version
  #     dnf:
  #       name:
  #         - openssh
  #         - openssh-server
  #         - openssh-clients
  #       state: latest
  #       update_cache: yes
  #   - name: Ensure /etc/hosts contains correct entry for FreeIPA
  #     lineinfile:
  #       path: /etc/hosts
  #       line: "10.0.1.110 ipa-server.rts.local ipa-server"
  #       state: present

  #   - name: Configure FreeIPA DNS as primary resolver
  #     lineinfile:
  #       path: /etc/resolv.conf
  #       line: "nameserver 10.0.1.110"
  #       create: yes
  #   - name: Set a hostname
  #     ansible.builtin.hostname:
  #       name: ipa-server.rts.local
  #   - name: Set SELinux to disabled state
  #     ansible.builtin.selinux:
  #       state: disabled
  #   - name: Install freeipa-server package
  #     yum:
  #       name:
  #         - freeipa-server
  #         - freeipa-server-dns
  #       state: present
  #       update_cache: yes
  #   - name: Add entry to /etc/hosts
  #     lineinfile:
  #       path: /etc/hosts
  #       line: "10.0.1.110 ipa-server.rts.local"
  #     # - name: Add entry to /etc/hosts
  #     #   lineinfile:
  #     #     path: /etc/hosts
  #     #     line: "18.196.176.246 ipa-server.rts.local"
  #     register: hosts_file
  #   - name: Run ipa-server-install command
  #     ansible.builtin.command: "ipa-server-install -U --mkhomedir -r RTS.LOCAL -n rts.local -p admin2023 -a admin2023 --hostname=ipa-server.rts.local --ip-address=10.0.1.110 -N --setup-dns --no-forwarders --no-reverse"
  #     when: hosts_file.changed
