---
all:
  children:
    ipaserver:
      hosts:
        10.0.1.110:
          ansible_hostname: ipaserver
      vars:
        # ansible_user: ec2-user
        # ansible_ssh_private_key_file: ~/Downloads/rke2-islam.pem
        ansible_become: yes
