---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt

platforms:
  - name: centos8-helm
    box: generic/centos8
    memory: 1024
    cpus: 1
    groups:
      - default
    instance_raw_config_args:
      - "vm.box_check_update = false"
    config_options:
      ssh.keep_alive: yes

provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
    ansible_become: true
  log: true
  lint:
    name: ansible-lint
    enabled: "true"
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
  inventory:
    host_vars:
      centos8-helm:

verifier:
  name: ansible
lint: |
  yamllint .
  ansible-lint .