---
# tasks file for nfs_sc
- name: Install pip package manager
  package:
    name: python3-pip
    state: present
  become: true

- name: Install required Python libraries
  pip:
    name:
      - kubernetes
      - PyYAML
      - jsonpatch
    state: present
  become: true

- ansible.builtin.template:
    src: nfs-kubernetes.yml
    dest: /home/{{ ansible_user }}/nfs-kubernetes.yml
- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: nfs
    api_version: v1
    kind: Namespace
    state: present
    validate_certs: no
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
- name: apply the manifest
  kubernetes.core.k8s:
    state: present
    src: nfs-kubernetes.yml
    validate_certs: no
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
