---
- name: Restart rke2-server
  ansible.builtin.systemd:
    name: rke2-server
    state: restarted
  become: true
  when: "'servers' in group_names"

- name: Restart rke2-agent
  ansible.builtin.systemd:
    name: rke2-agent
    state: restarted
  become: true
  when: "'agents' in group_names"