---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install python3-pip
  apt:
    name: python3-pip
    state: present

- name: Install kubernetes Python package via pip3
  pip:
    name: kubernetes
    executable: pip3