# bootstraps first server and copies configs for others/agents
- name: Prepare all nodes
  hosts: rke2
  gather_facts: false # fact gathering is slow and not needed for any of our tasks
  become: true
  roles:
    - prepare-nodes
    - rke2-download

# bootstraps the first server, copies configs to nodes, saves token to use later
- name: Prepare RKE2 on Servers and Agents
  hosts: servers,agents
  gather_facts: true
  roles:
    - rke2-prepare

# Adds additional servers using the token from the previous task
- name: Add additional RKE2 Servers
  hosts: servers
  gather_facts: true
  roles:
    - add-server

# Adds agents to the cluster
- name: Add additional RKE2 Agents
  hosts: agents
  gather_facts: true
  roles:
    - add-agent

- name: increase file limits
  hosts: agents
  become: true
  gather_facts: true
  roles:
    - file-limits-increaser